name: auto-grading

on:
  push:
    branches:
      - main
      - master

env:
  CARGO_TERM_COLOR: always


jobs:

  basic-test:

    name: ArceOS Test

    runs-on: ubuntu-latest

    outputs:
      score: ${{ steps.score.outputs.score }}


    steps:

      - uses: actions/checkout@v4


      - uses: Swatinem/rust-cache@v2


      - name: Install dependencies

        run: |

          sudo apt-get update

          sudo apt-get install -y \
            wget \
            xxd \
            curl \
            gcc \
            g++ \
            make \
            libclang-dev \
            qemu-system-misc \
            bash \
            git \
            dosfstools \
            build-essential \
            pkg-config \
            libssl-dev \
            libz-dev



      - name: Setup musl

        uses: arceos-org/setup-musl@v1

        with:

          arch: riscv64



      - name: Setup Rust

        uses: dtolnay/rust-toolchain@stable

        with:

          toolchain: nightly-2024-09-04

          components:
            rust-src,
            llvm-tools,
            clippy,
            rustfmt

          targets:
            x86_64-unknown-none,
            riscv64gc-unknown-none-elf,
            aarch64-unknown-none,
            aarch64-unknown-none-softfloat,
            loongarch64-unknown-none



      - name: Setup binutils

        run: |

          SYSROOT=$(rustc --print sysroot)

          LLVM_BIN="$SYSROOT/lib/rustlib/x86_64-unknown-linux-gnu/bin"


          ln -sf \
          "$LLVM_BIN/llvm-objcopy" \
          ~/.cargo/bin/rust-objcopy


          ln -sf \
          "$LLVM_BIN/llvm-objdump" \
          ~/.cargo/bin/rust-objdump



      - name: Run Tests

        run: |


          qemu-system-riscv64 --version


          cd arceos

          cargo update -p indexmap --precise 2.6.0

          cd ..


          ./scripts/total-test.sh | tee result.txt



      - name: Calculate Score

        id: score

        run: |


          SCORE=$(tail -n1 result.txt)


          echo "score=$SCORE" >> $GITHUB_OUTPUT


          echo ""

          echo "=============================="

          echo "      ArceOS Score"

          echo "      $SCORE"

          echo "=============================="




      - name: Show Result

        run: |


          echo "## 🎯 ArceOS Auto Grading Result" >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY


          echo "| Item | Result |" >> $GITHUB_STEP_SUMMARY

          echo "|---|---|" >> $GITHUB_STEP_SUMMARY

          echo "| Score | ${{ steps.score.outputs.score }} |" >> $GITHUB_STEP_SUMMARY


          echo "" >> $GITHUB_STEP_SUMMARY


          cat result.txt >> $GITHUB_STEP_SUMMARY
